name: New Aggregator Platform
description: Request to add new aggregator platform
title: "[Service Request] Add new platform NEW_PLATFORM_NAME"
labels: ["service-request", "API"]
assignees:
  - vrajroham
body:
  - type: markdown
    attributes:
      value: |
        Add following details for the new platform/aggregator you want to add on Prime.
  - type: input
    id: name
    attributes:
      label: Platform Name
      description: What is the platform name?
      placeholder: ex. Uber Eats
    validations:
      required: true
  - type: input
    id: platformname
    attributes:
      label: Platform Key
      description: What is the **platform-key** that Codex will send in downstream playload?
      placeholder: ex. ubereats
    validations:
      required: true
  - type: textarea
    attributes:
      label: Platform Logo
      description: |
        Attach the platform logo. It would be better if you provided logo in 512x512px format(optional)

        Tip: You can attach logo or additional files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Anything else?
      description: Would you like to share anything else along with the request. E.g. Similar request made in past?

